# Generated by Django 3.0 on 2020-06-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200623_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatter',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=2),
        ),
    ]
