# Generated by Django 3.0 on 2020-06-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dinnerplatter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.DinnerPlatter'),
        ),
    ]
