# Generated by Django 3.0 on 2020-06-30 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200630_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subextra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.SubExtra'),
        ),
    ]
